### ISSUE TITLE
ADO pipeline not deploying App GW, Hello World App

### ISSUE THREAD

**Issue by sowsan** [Azure/aca-landing-zone-accelerator#118]
Configured the parameter file as default setting to deploy hello world app. I am not seeing it is getting deployed and no App Gateway deployed. Pipeline itself completed successfully. If this needs to be configured separately any guidelines on how to deploy Frontdoor or App Gateway using ADO or Github pipelines ?

**Comment by thotheod** [comment]
you are correct, the pipelines do not deploy any app Gateway. Since a Reverse App Proxy (App Gateway) is considered part of the application we chose to give the user the option to select whether they need to deploy any sample app, such as one of the following
- https://github.com/Azure/aca-landing-zone-accelerator/blob/main/scenarios/aca-internal/bicep/sample-apps/dotnet-task-tracker-service/docs/02-container-apps.md
- https://github.com/Azure/aca-landing-zone-accelerator/blob/main/scenarios/aca-internal/bicep/sample-apps/java-fine-collection-service/docs/02-container-apps.md
